name: Executar Live Scanner HT

on:
  schedule:
    # Roda a cada 5 minutos entre 17:00 UTC (14:00 BR) e 01:00 UTC (22:00 BR)
    # Cobre perfeitamente a janela de 8 horas gastando exatamente 96 requisições por dia
    - cron: '*/5 17-23 * * *'
    - cron: '*/5 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scanner-futebol:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar o projeto do Git
      uses: actions/checkout@v3

    - name: Instalar Python do Sistema
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Carregar dependencias estatisticas
      run: |
        pip install requests pandas numpy pytz

    - name: Executar Monitoramento de Alta Frequencia
      run: python scanner.py
